### ISSUE TITLE
Instruction to compile .car file

### ISSUE THREAD

**Issue by dangh** [tsujp/custom-macos-gui#1]
Hello,

Thank you for your awesome work. It was working perfectly on macOS 10.15 but unfortunately the provided .car stopped working on macOS 10.15.1

Can you point me to a resource/tutorial on how to modify the .car file?

Cheers!

**Comment by tsujp** [comment]
@dangh sorry for the long reply mate, I missed this somehow.

I cannot make a more detailed guide right now but I used `Asset Catalog Tinkerer.app` from https://github.com/insidegui/AssetCatalogTinkerer to edit the appropriate `.car` files within the `SystemAppearance.bundle` package. There are instructions on their repo on how to use the tool and the paths to the file, and the path *within* that package is the directory structure of this repo.

In summary though the path you're interested in, as a baseline, is `/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources`. You can reach that by pressing `CMD + SHIFT + G` on a Finder window – including the dropdown on dialogue boxes such as "Open..." or "Save..." for instance as they are of course Finder windows too. Or you can just `cd` there and `open -a Finder .` to open the directory since the tool is GUI only.

Once there you'll see a whole bunch of `.car` files, back to the directory structure of this repo you'll see a `DarkAquaAppearance.car` file, open that with Asset Catalog Tinkerer. On the list of assets you can edit you should edit the `WindowFrame_WindowShapeEdges` group because the path in this repo is `DarkAquaAppearance/WindowFrame_WindowShapeEdges/`.


Let me know how you go.

**Comment by tsujp** [comment]
Closing as it's been a few months. If there is a follow up just comment and we can further discuss and I can reopen the issue.

**Comment by dortamiguel** [comment]
How I can edit the car file with AssetCatalogTinkerer?

I can only drag and drop images outside of the app

**Comment by tsujp** [comment]
@ellipticaldoor You'll have to export the images, edit them, then re-import them. AssetCatalogTinkerer is just for getting the images in and out, any edits occur in either Photoshop, Sketch, Figma, or whatever other editor you want to use.

**Comment by dortamiguel** [comment]
but how you re-import? I want to use the images you have in the repo, but I can't find how to place them

**Comment by dortamiguel** [comment]
In the end used ThemeEngine from latest master to edit the file, now I have sharp corners :)

**Comment by dortamiguel** [comment]
Do you know how to remove the white border on the windows in dark mode too?

**Comment by CrisVM** [comment]
I just stumbled upon **square-macos-windows** and I love it! It's really awesome!

This should be the default, or at the very least be configurable in System Preferences.

It's a much needed fix when we have to use Mojave patcher and get all those glitchy window corners by default... _(I'm using a 2011 MacBook Pro and Mojave doesn't support it officially)_

It's a shame **Spotlight** doesn't take advantage of this fix...
https://drive.google.com/open?id=12-X6c_XuZeR79xWnMbO5l_bhcmp9oy8w

Excellent job you've done! KUDOS!

**Comment by tsujp** [comment]
@ellipticaldoor the white border is a separate file which is hard to see in the list, it's a transparent single-pixel line which is applied to the edge of windows.

@CrisVM thanks mate!

What I am going to do I think is update this for the latest macOS and do all the possible themes, and see if I can get it working with Spotlight. I mainly use Linux nowadays and when I was on macOS I used Alfred instead of Spotlight but I do need to "complete" this repo as it were.

**Comment by dortamiguel** [comment]
> @ellipticaldoor the white border is a separate file which is hard to see in the list, it's a transparent single-pixel line which is applied to the edge of windows.
> 
> @CrisVM thanks mate!
> 
> What I am going to do I think is update this for the latest macOS and do all the possible themes, and see if I can get it working with Spotlight. I mainly use Linux nowadays and when I was on macOS I used Alfred instead of Spotlight but I do need to "complete" this repo as it were.

oh nice! do you know which file is and how I can edit it?

**Comment by tsujp** [comment]
I forgot the name but I will find out later today/tomorrow.

**Comment by dortamiguel** [comment]
Thank you very much! I've been looking for this a long time

**Comment by dortamiguel** [comment]
I'm trying to find the file but not luck to the moment, do you remember any clue or file?

**Comment by kvndrsslr** [comment]
Hey guys, thanks @tsujp for your work! I discovered this a week ago as I also wanted to improve the look of my yabai setup.
With Big Sur being announced with a complete UI redesign I was very annoyed as they made the corner radius even bigger..
So I went on a quest to bring square-corners to Big Sur and it worked! Its described in #2 and I will do a PR when Big Sur gets released. 🎉

**Comment by tsujp** [comment]
Sounds good mate @kvndrsslr 

Sorry @ellipticaldoor I've been mucho busy lately, I'll get on this this week so you have all the files. I cannot remember what it was called, but will re-find out shortly.

**Comment by dortamiguel** [comment]
Thanks @tsujp

**Comment by CrisVM** [comment]
I was just wondering if it's possible to make menus' corners to be square as well... What do you think?
https://drive.google.com/file/d/1RSYaYoHnPgEGI7Mx9J-W0o9TNeUpzB2F/view?usp=sharing

Cheers.

**Comment by tsujp** [comment]
Probably. I can get round to that too, should be updating my machine to Catalina finally; had a lot of things to do recently so I've been putting it off.

**Comment by tsujp** [comment]
I am installing Big Sur right now and will be adding lots more to the repo either tonight (if all goes well) or very soon, I plan to only support Big Sur and onwards since thats the latest macOS coming out. Let's do this!

I've locked this issue only to prevent it becoming a "chat-like" issue, please make a new one with a defined scope since we drifted from the topic of instructions for creating .car files here.
