### ISSUE TITLE
is this repo supports for osx monterey light theme?

### ISSUE THREAD

**Issue by ghost** [tsujp/custom-macos-gui#8]
I checked /System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources
there are only three files prefix DarkAuqa : DarkAqua.car  DarkAquaAX.car DarkAquaVisibleBezels.car
so what am I supposed to do with this repo's DarkAquaAppearence.car and is it supported for light theme?

**Comment by tsujp** [comment]
I can double check, it should work but the files might need a rename. I'll check this week and get back to you.

**Comment by ghost** [comment]
@tsujp just a reminder ^^

**Comment by tsujp** [comment]
> @tsujp just a reminder ^^

It fell off my todo-list as I am a chronic yak-shaver, whoops!

I had a look today; the `AX` is Apple's accessibility API so that'll be theming related to that. `DarkAqua.car` is the asset file we're interested in here; going to patch and confirm tomorrow.

**Comment by tsujp** [comment]
Still doing this; I want to do it programmatically so I am doing some image creation (the masks Aqua uses to form the corner radii) in C; give me a bit as I dust off that.

Also sets up some future things which will be nice.

**EDIT**: Actually no I will finish the patch and upload them so you have the changes early since looking into this more the programmatic image creation will still require manual intervention until I get an API for editing .car files going.

**Will finish this by Friday.**

**Comment by tsujp** [comment]
Tag `v0.1.0` should have patched `.car` files which work now. Can you confirm they work for you too?

See: https://github.com/tsujp/customise_macos/releases/tag/v0.1.0 you'll want the ones in the `appearance/Aqua` and/or `appearance/DarkAqua` folders.
